# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id_banco', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nit', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
