# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id_cajero', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_banco', models.IntegerField()),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ubicacion', models.CharField(max_length=45)),
                ('ind_servicio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('numero', models.CharField(max_length=45)),
                ('id_banco', models.IntegerField()),
                ('id_producto', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('id_estado', models.IntegerField()),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('clave', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_detalle', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_transaccion', models.IntegerField()),
                ('id_movimiento', models.IntegerField()),
                ('id_cuenta', models.IntegerField()),
                ('id_tarjeta', models.IntegerField()),
                ('monto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id_tarjeta', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('numero', models.CharField(max_length=45)),
                ('id_cuenta', models.IntegerField()),
                ('id_estado', models.IntegerField()),
                ('valithru', models.DateTimeField(verbose_name='date published')),
                ('ind_block', models.IntegerField()),
                ('clave', models.CharField(max_length=45)),
                ('fec_creacion', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_identificacion',
            fields=[
                ('id_identificacion', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_cajero', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(verbose_name='date published')),
                ('ind_estado', models.IntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('identificacion', models.CharField(max_length=15)),
                ('tipo_identificacion', models.IntegerField()),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('celular', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateTimeField(verbose_name='date published')),
                ('fecha_actualizacion', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
