# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0002_cajero_cuenta_detalle_estado_movimiento_producto_tarjeta_tipo_identificacion_transaccion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajero',
            name='id_banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.Banco'),
        ),
    ]
