# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0003_auto_20190529_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='id_banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.Banco'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.Estado'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.Producto'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.usuario'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='id_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.Cuenta'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='id_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.Movimiento'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='id_tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.Tarjeta'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='id_transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.Transaccion'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='id_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.Cuenta'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.Estado'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_cajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.Cajero'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='ind_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.Tipo_identificacion'),
        ),
    ]
